apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: img-prem-302
  namespace: default
  labels:
    app: svi-302
  annotations:
    autoscaling.knative.dev/target: "1"
    autoscaling.knative.dev/targetUtilizationPercentage: "95"
    autoscaling.knative.dev/window: "50s"
    autoscaling.knative.dev/panicWindowPercentage: "95"
    autoscaling.knative.dev/panicThresholdPercentage: "190"
    autoscaling.knative.dev/scaleDownDelay: "200s"
    autoscaling.knative.dev/target-burst-capacity: "1"
spec:
  predictor:
    containerConcurrency: 1
    minReplicas: 15
    maxReplicas: 15
    runtimeClassName: nvidia
    containers:
    - name: svi
      image: registry.vyro-dfw-1.lstn.net/svi_301:1.2.7
      startupProbe: 
        tcpSocket:
          port: 8012
        initialDelaySeconds: 30
        periodSeconds: 15
      readinessProbe:
        tcpSocket:
          port: 8080
        initialDelaySeconds: 3
        periodSeconds: 5
      resources:
        requests:
          cpu: 15
          memory: 30Gi
          nvidia.com/gpu: 1
        limits:
          cpu: 30
          memory: 60Gi
          nvidia.com/gpu: 1
      env:
      - name: STORAGE_URI
        value: pvc://vyro-models-lga/
      - name: MODEL_PATH
        value: '/mnt/pvc/models/svi/models'
      - name: STYLE_ID
        value: '302'
      - name: MODELS_DIRECTORY
        value: '/mnt/pvc/models/svi/models/302_svi4'
      - name: CONFIG_PATH
        value: '/mnt/pvc/models/svi/models/config'
      - name: LORA_IDENTIFIER
        value: '<effect>'
      - name: LORA_STRENGTH_MULTIPLIER
        value: '0.2'
      - name: SERVICE_NAME
        value: 'ml-svi'
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: 'http://143.244.212.132:4318'
      - name: OTEL_EXPORTER_OTLP_HEADERS
        value: 'Authorization=Basic YWRtaW46dnlyby1hZG1pbg=='
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: 'http/protobuf'
      - name: JWT_VALID_TOKENS
        value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtbC10ZWFtIiwiaWF0IjoxNzMyODE0ODg2LCJleHAiOjE3NDA1OTA4ODYsImp0aSI6ImQ1NzI3YWU4YTEyMmJhNjcwZTc4MDMyNWI4Y2E5MmY5Iiwicm9sZSI6ImFkbWluIn0.DYR6roeo8YiEDUAvcVZGHY5sYcY5yzpTPuuqLxcZ8Wc"
      - name: IGNORE_CMD_ARGS_ERRORS
        value: 'true'
      - name: IP_ADAPTER_WEIGHT_TYPE
        value: 'original'
      - name: STYLE_STRENGTH
        value: '1.0'
      - name: ASPECT_RATIO
        value: 'old-sdxl'
    imagePullSecrets:
    - name: vyro-registry